FROM python:3.11-slim

# Instalar Java (necessário para Spark)
RUN apt-get update && apt-get install -y openjdk-11-jdk && rm -rf /var/lib/apt/lists/*
ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64

# Instalar PySpark
RUN pip install pyspark

# Configurar diretório de trabalho
WORKDIR /app

# Copiar script
COPY script_pyspark.py .

# Comando padrão
CMD ["python", "script_pyspark.py"]